export enum QueryKeys {
  GET_NOTES = "GET_NOTES",
  GET_NODE_BY_ID = "GET_NODE_BY_ID",
  GET_FAVORITE_NOTES = "GET_FAVORITE_NOTES",
  GET_USER_ACTIVITY_SUMMARY = "GET_USER_ACTIVITY_SUMMARY",
  GET_ORGANIZATION_MEMBERS = "GET_ORGANIZATION_MEMBERS",
  GET_ORGANIZATION_INVITATIONS = "GET_ORGANIZATION_INVITATIONS",
  GET_INVITATION_BY_ID = "GET_INVITATION_BY_ID",
  GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID",
  GET_PROJECTS = "GET_PROJECTS",
}
